### ISSUE TITLE
'make test' doesn't appear to run all tests

### ISSUE THREAD

**Issue by raboof** [janestreet/core_kernel#44]
Not when I first do `./configure --enable-tests`, either.

Tested by intentionally breaking a test (`time_ns.ml:374`) and running `./configure --enable-tests; make clean; make test`

I'm probably missing something, but perhaps that can be better documented? :)

**Comment by bmillwood** [comment]
I'm not surprised. Internally we have jenga run the tests for us, and the whole ocamlbuild setup is much less cared-for. A medium-term goal is to make it possible/easy for external contributors to use jenga to compile our libraries, too; I don't think I'll want to work on getting ocamlbuild to run the tests before that's happened.

**Comment by raboof** [comment]
That makes total sense! 

I haven't looked into jenga yet, is there anything in particular that makes it impossible for me to use it to build core_kernel?

**Comment by bmillwood** [comment]
It's certainly not impossible, but you'd probably have to reinvent some of the work we've already done and just not worked out how to release yet -- there are some jenga metadata files that we maintain internally and plan to include in a future release but haven't worked out the details yet.

Plus, of course, the *first* build can't be with Jenga, since you need to install core_kernel to install Jenga :)

**Comment by hhugo** [comment]
waitting for https://github.com/janestreet/jbuilder/pull/338

**Comment by acatton** [comment]
Is this ticket still valid? As far as I can tell, `make test` does not exist anymore and has been replaced by `jbuilder runtest`.

**Comment by raboof** [comment]
I haven't kept up with the project, feel free to close when this ticket is now obsolete

**Comment by bcc32** [comment]
Closing, thanks.
