### ISSUE TITLE
Bigbuffer and bigstring questions

### ISSUE THREAD

**Issue by samoht** [janestreet/core_kernel#7]
Just started using Bigbuffer and bigstring and I quite like them. I have few questions/concerns that I note here to not forget them.
- `Bigbuffer.volatile_contents` is quite confusing. I would expect it to return a consistent subview of the underlying bigarray (with the right length), not the whole bigarray. I had to wrap it into something like `Bigstring.sub_share ~len:(Bigbuffer.length b) (Bigbuffer.volatile_contents b)`;
- There are no `Bigbuffer.add_bigstring`. I had to do `Bigbuffer.add_string (Bigstring.to_string s)` which means extra allocations;
- slighlty related, there are no `Bigstring.concat: t list -> t`;
- bigstrings and bigbuffers are not comparable, and bigbuffers are not binable;
- a more general concern is that would be very handy to have an good way to interface bigbuffers and [ocplib-endian](https://github.com/ocamlpro/ocplib-endian) to be able to add ints whithout having to allocate an intermediate string everytime.

**Comment by seliopou** [comment]
This is pretty old. I think most of the the issues bought up have since been resolved:

1. you can use [`Bigbuffer.big_contents`](https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/Core_kernel/Bigbuffer/index.html#val-big_contents) rather than `Bigbuffer.volatile_contents` to get the behavior you expected;
2. there is now a [`Bigbuffer.add_bigstring`](https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/Core_kernel/Bigbuffer/index.html#val-add_bigstring);
3. there is now a [`Bigstring.concat`](https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/Core_kernel/Bigstring/index.html#val-concat);
4. `Bigstring.t` is now comparable, though `Bigbuffer.t` is not (and I'd say that's intentional), and both are now binable;
5. `Bigbuffer` doesn't have the sort of operations that [`Bigstring` supports](https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/Core_kernel/Bigstring/index.html#accessors-for-parsing-binary-values,-analogous-to-binary_packing). If this is still something that'd be of interest, feel free to open a separate issue for it and we can look into adding the missing operations.
